EtnoSelo.App/Controllers/PregledKlijenataController.cs
using EtnoSelo.App.Models;
using EtnoSelo.App.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EtnoSelo.App.Controllers
{
    public class PregledKlijenataController : Controller
    {
        // GET: PregledKlijenta
        public ActionResult Index()
        {
            var model = new PretragaKlijenataModel();

            var korisnikServis = new KorisnikServis();

            model.Klijenti = korisnikServis.DobaviSveKlijente();

            return View(model);
        }

        public ActionResult Pretraga(string imePrezime)
        {
            var model = new PretragaKlijenataModel();
            model.ImePrezime = imePrezime;

            var korisnikServis = new KorisnikServis();

            //Ako ime ili prezime nije uneseno vrati sve rezultate
            if(string.IsNullOrWhiteSpace(imePrezime))
                model.Klijenti = korisnikServis.DobaviSveKlijente();
            //Inace filtriraj po imenu i/ili prezimenu
            else
                model.Klijenti = korisnikServis.DobaviKlijentePoImenuIPrezimenu(imePrezime);

            return View("Index", model);
        }

        public ActionResult Detalji(int klijentId)
        {
            var korisnikServis = new KorisnikServis();

            var model = korisnikServis.DobaviKlijentaPoId(klijentId);

            return View(model);
        }
    }
}

EtnoSelo.App/Views/PregledKlijenata/Detalji.cshtml
@model EtnoSelo.App.Models.KlijentModel
<div class="panel panel-primary">
    <div class="panel-heading">Detalji o klijentu</div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Ime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Prezime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Prezime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Telefon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telefon)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Grad)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Grad)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Drzava)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Drzava)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DatumRodjenja)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Aktivan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Aktivan)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Nazad", "Index", new { }, new { @class = "btn btn-default" })
    </p>
</div>

EtnoSelo.App/Views/PregledKlijenata/Index.cshtml
@model EtnoSelo.App.Models.PretragaKlijenataModel

<div class="panel panel-primary">
    <div class="panel-heading">Pretraga Klijenata</div>
    <div class="panel-body">
        @using (Html.BeginForm("Pretraga", "PregledKlijenata"))
        {
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ImePrezime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.ImePrezime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ImePrezime, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-1">
                        <input type="submit" value="Pretrazi" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Klijenti.FirstOrDefault().Ime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Klijenti.FirstOrDefault().Prezime)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Klijenti)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prezime)
                    </td>
                    <td>
                        @Html.ActionLink("Detalji", "Detalji", new { klijentId = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>