EtnoSelo.App/Controllers/PonudeController.cs
using EtnoSelo.App.Models;
using EtnoSelo.App.Services;
using EtnoSelo.App.Shared;
using EtnoSelo.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EtnoSelo.App.Controllers
{
    public class PonudeController : Controller
    {
        PonudaServis _ponudaServis;
        public PonudeController()
        {
            _ponudaServis = new PonudaServis();
        }
        // GET: Ponude
        public ActionResult Index()
        {
            var model = _ponudaServis.DobaviAktivnePonude();

            return View(model);
        }

        public ActionResult Uredi(int id)
        {
            var ponuda = InicijalizujPonuduPoId(id);

            SessionFacade.AktivnaPonuda = ponuda;

            return View("KreirajPonudu", ponuda);
        }

        public ActionResult Detalji(int id)
        {
            var ponuda = InicijalizujPonuduPoId(id);

            SessionFacade.AktivnaPonuda = ponuda;

            ViewData["PreusmjeriNa"] = "Index";

            return View("PregledPonude", ponuda);
        }

        public ActionResult Obrisi(int id)
        {
            _ponudaServis.ObrisiPonuduPoId(id);
            return RedirectToAction("Index");
        }

        public ActionResult KreirajPonudu(bool kreirajNovu = true)
        {
            PonudaModel ponudaModel = null;

            if (!kreirajNovu)
                ponudaModel = SessionFacade.AktivnaPonuda;

            if (ponudaModel == null)
            {
                ponudaModel = new PonudaModel()
                {
                    VaziOd = DateTime.Now.Date.ToShortDateString(),//.ToString("dd/MM/yyyy").Replace('.', '/'),
                    VaziDo = DateTime.Now.Date.ToShortDateString(),//.ToString("dd/MM/yyyy").Replace('.', '/'),
                    Popust = 20,
                    PonudeJedinice = new List<PonudaJedinicaModel>()
                {
                    InicijalizujPonudaJedinicaModel()
                },
                    Aktivnosti = new List<PonudeAktivnostiModel>()
                {
                    new PonudeAktivnostiModel()
                    {
                        Aktivnost = int.Parse(_ponudaServis.DobaviSveAktivnosti().FirstOrDefault().Value),
                        Aktivnosti = _ponudaServis.DobaviSveAktivnosti()
                    }
                }
                };
            }

            SessionFacade.AktivnaPonuda = ponudaModel;

            return View(ponudaModel);
        }

        public ActionResult DodajPonudu(PonudaModel model)
        {
            //Inicijalizuj listu ako je null
            if (model.PonudeJedinice == null)
                model.PonudeJedinice = new List<PonudaJedinicaModel>();

            //Inicijalizuj listu ako je null
            if (model.Aktivnosti == null)
                model.Aktivnosti = new List<PonudeAktivnostiModel>();

            //dodaj Jedinicu
            if (model.Dodaj == 1)
                model.PonudeJedinice.Add(InicijalizujPonudaJedinicaModel());

            //else if model.dodaj == 2 dodaj aktivnost
            else
                model.Aktivnosti.Add(new PonudeAktivnostiModel()
                {
                    Aktivnost = int.Parse(_ponudaServis.DobaviSveAktivnosti().FirstOrDefault().Value),
                    Aktivnosti = _ponudaServis.DobaviSveAktivnosti()
                });

            //Populisi drodown liste za stanbene jedinice za svaku red
            foreach (var item in model.PonudeJedinice)
            {
                item.StanbeneJedinice = _ponudaServis.DobaviJediniceFiltriranePoTipuSmjestaja(item.TipStanbeneJedinice);
                item.TipoviStanbenihJedinica = _ponudaServis.DobaviTipoveSmjestaja();
            }

            //Populisti dropdwon listu aktivnosti za svaki red
            foreach (var item in model.Aktivnosti)
                item.Aktivnosti = _ponudaServis.DobaviSveAktivnosti();

            SessionFacade.AktivnaPonuda = model;

            return View("KreirajPonudu", model);
        }

        public ActionResult ObrisiStavkuIzPonude(PonudaModel model)
        {
            //Inicijalizuj listu
            if (model.PonudeJedinice == null)
                model.PonudeJedinice = new List<PonudaJedinicaModel>();
            //Inicijalizuj listu
            if (model.Aktivnosti == null)
                model.Aktivnosti = new List<PonudeAktivnostiModel>();

            //Pronadji jedinicu sa prosljedjenim Guidom i izbrisi je ako postoji
            var tempModel = model.PonudeJedinice.FirstOrDefault(x => x.MyGuid == model.Guid);
            if (tempModel != null)
                model.PonudeJedinice.Remove(tempModel);
            
            //Pronadji aktivnosti sa porsljedjenim Guidom i izbrisi je ako postoji
            var tempModel2 = model.Aktivnosti.FirstOrDefault(x => x.MyGuid == model.Guid);
            if(tempModel2 != null)
                    model.Aktivnosti.Remove(tempModel2);


            //Populisi drodown liste za stanbene jedinice za svaku red
            foreach (var item in model.PonudeJedinice)
            {
                item.StanbeneJedinice = _ponudaServis.DobaviJediniceFiltriranePoTipuSmjestaja(item.TipStanbeneJedinice);
                item.TipoviStanbenihJedinica = _ponudaServis.DobaviTipoveSmjestaja();
            }

            //Populisti dropdwon listu aktivnosti za svaki red
            foreach (var item in model.Aktivnosti)
                item.Aktivnosti = _ponudaServis.DobaviSveAktivnosti();

            SessionFacade.AktivnaPonuda = model;

            return View("KreirajPonudu", model);
        }

        public ActionResult PregledPonude(PonudaModel model)
        {
            //Inicijalizuj listu
            if (model.PonudeJedinice == null)
                model.PonudeJedinice = new List<PonudaJedinicaModel>();
            //Inicijalizuj listu
            if (model.Aktivnosti == null)
                model.Aktivnosti = new List<PonudeAktivnostiModel>();

            //Populisi drodown liste za stanbene jedinice za svaku red
            foreach (var item in model.PonudeJedinice)
            {
                item.StanbeneJedinice = _ponudaServis.DobaviJediniceFiltriranePoTipuSmjestaja(item.TipStanbeneJedinice);
                item.TipoviStanbenihJedinica = _ponudaServis.DobaviTipoveSmjestaja();
                float tempVal = 1 - (float)model.Popust / 100;
                item.CijenaSaPopustom = tempVal * item.CijenaBezPopusta;
            }

            //Populisti dropdwon listu aktivnosti za svaki red
            foreach (var item in model.Aktivnosti)
                item.Aktivnosti = _ponudaServis.DobaviSveAktivnosti();

            //Ako model nije validan vrati poruku nazad
            if(!ModelState.IsValid)
                return View("KreirajPonudu", model);

            //Ako model ne sadrzi niti jednu jedinicu onda nije validan i prikazi poruku
            if (model.PonudeJedinice.Count < 1)
            {
                ModelState.AddModelError("", "Ponuda mora sadrzavati najmanje jednu jedinicu!!!");
                return View("KreirajPonudu", model);
            }

            SessionFacade.AktivnaPonuda = model;

            ViewData["PreusmjeriNa"] = "KreirajPonudu";

            return View(model);
        }

        public ActionResult Snimi()
        {
            _ponudaServis.DodajPonudu(SessionFacade.AktivnaPonuda);

            return RedirectToAction("Index");
        }

        public JsonResult DobaviStanbeneJedinice(int tipStanbeneJedinice)
        {
            var jedinice = _ponudaServis
                    .DobaviJediniceFiltriranePoTipuSmjestaja(tipStanbeneJedinice);

            return Json(jedinice, JsonRequestBehavior.AllowGet);
        }

        #region privatne metode

        /// <summary>
        /// Inicijalizuj model sa pocetnim vrijednostima
        /// </summary>
        /// <returns>Inicijalizovani model</returns>
        private PonudaJedinicaModel InicijalizujPonudaJedinicaModel()
        {
            try
            {
                var tipoviSmjestaja = _ponudaServis.DobaviTipoveSmjestaja();

                var jedinice = _ponudaServis
                    .DobaviJediniceFiltriranePoTipuSmjestaja(int.Parse(tipoviSmjestaja.FirstOrDefault().Value));

                var tempModel = new PonudaJedinicaModel()
                {
                    TipStanbeneJedinice = int.Parse(tipoviSmjestaja.FirstOrDefault().Value),
                    TipoviStanbenihJedinica = tipoviSmjestaja,
                    StanbeneJedinice = jedinice,
                    StanbenaJedinica = jedinice.FirstOrDefault().Id,
                    CijenaBezPopusta = jedinice.FirstOrDefault().Cijena,
                    //Uracunaj inicijalni popust od 20%
                    CijenaSaPopustom = (float)(jedinice.FirstOrDefault().Cijena * 0.8)
                };

                return tempModel;
            }
            catch (Exception ex)
            {
                LoggingHelper.Greska(ex, nameof(PonudeController), nameof(InicijalizujPonudaJedinicaModel));
                return null;
            }
        }

        private PonudaModel InicijalizujPonuduPoId(int id)
        {
            var ponuda = _ponudaServis.DobaviPonuduPoId(id);

            //Populisi drodown liste za stanbene jedinice za svaku red
            foreach (var item in ponuda.PonudeJedinice)
            {
                item.StanbeneJedinice = _ponudaServis.DobaviJediniceFiltriranePoTipuSmjestaja(item.TipStanbeneJedinice);
                item.TipoviStanbenihJedinica = _ponudaServis.DobaviTipoveSmjestaja();
            }

            //Populisti dropdwon listu aktivnosti za svaki red
            foreach (var item in ponuda.Aktivnosti)
                item.Aktivnosti = _ponudaServis.DobaviSveAktivnosti();

            ponuda.NaziviSlika = Helpers.Helpers.DobaviImenaNaziveSlikaZaPonudu(id);

            return ponuda;
        }

        #endregion
    }
}

EtnoSelo.App/Views/Ponude/Index.cshtml
@model IEnumerable<EtnoSelo.App.Models.PonudaModel>

<div class="panel panel-primary">
    <div class="panel-heading">Detalji o klijentu</div>
    <div class="panel-body">
        <p>
            @Html.ActionLink("Kreiraj ponudu", "KreirajPonudu")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DatumKreiranja)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VaziOd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VaziDo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Popust)
                </th>                
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumKreiranja)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VaziOd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VaziDo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Popust)
                    </td>                    
                    <td>
                        @Html.ActionLink("Uredi", "Uredi", new { id = item.Id })  |
                        @Html.ActionLink("Detalji", "Detalji", new { id = item.Id }) |
                        @Html.ActionLink("Obrisi", "Obrisi", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

EtnoSelo.App/Views/Ponude/KreirajPonudu.cshtml
@model EtnoSelo.App.Models.PonudaModel

<div class="panel panel-primary">
    <div class="panel-heading">Dodaj Novu Ponudu</div>
    <div class="panel-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @using (Html.BeginForm("DodajPonudu", "Ponude", FormMethod.Post, new { id = "frmDodajPonudu", enctype = "multipart/form-data" }))
        {
            <input type="hidden" id="Dodaj" name="Dodaj" />
            @Html.HiddenFor(x=>x.Id)

            @Html.HiddenFor(x => x.Guid)

            <div class="form-inline">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.VaziOd, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.VaziOd, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VaziOd, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.VaziDo, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.VaziDo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VaziDo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <br />
            <div class="form-horizontal" style="margin-left:30px;">
                <hr />
                <h4>Stanbene Jedinice</h4>
                <table id="tblJedinice" width="900">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th colspan="3">Cijena bez/sa popustom</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.PonudeJedinice.Count; i++)
                        {
                            <tr>
                                <td width="40%">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            @Html.DropDownListFor(model => model.PonudeJedinice[i].TipStanbeneJedinice, new SelectList(Model.PonudeJedinice[i].TipoviStanbenihJedinica, "Value", "Text", Model.PonudeJedinice[i].TipStanbeneJedinice), new { @class = "form-control", @onchange = "ucitajStanbeneJedinice(this)", @name = $"[{i}].TipStanbeneJedinice" })
                                            @Html.ValidationMessageFor(model => model.PonudeJedinice[i].TipStanbeneJedinice, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </td>
                                <td width="40%">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            @*@Html.DropDownListFor(model => model.PonudeJedinice[i].StanbenaJedinica, Model.PonudeJedinice[i].StanbeneJedinice.Select(x => new SelectListItem() { Text = x.Naziv, Value = x.Id.ToString() }).ToList(), new { @class = "form-control", @name = $"[{i}].StanbenaJedinica" })*@
                                            @Html.DropDownListFor(model => model.PonudeJedinice[i].StanbenaJedinica, new SelectList(Model.PonudeJedinice[i].StanbeneJedinice, "Id", "Naziv", Model.PonudeJedinice[i].StanbenaJedinica), new { @class = "form-control", @name = $"[{i}].StanbenaJedinica" })
                                            @Html.ValidationMessageFor(model => model.PonudeJedinice[i].StanbenaJedinica, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </td>

                                <td width="10%">
                                    <div class="form-group">
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.PonudeJedinice[i].CijenaBezPopusta, new { htmlAttributes = new { @class = "form-control", @onchange = "izracunajPopust()" } })
                                            @Html.ValidationMessageFor(model => model.PonudeJedinice[i].CijenaBezPopusta, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </td>

                                <td width="10%">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.PonudeJedinice[i].CijenaSaPopustom, new { htmlAttributes = new { @class = "form-control", disabled = "" } })
                                            @Html.ValidationMessageFor(model => model.PonudeJedinice[i].CijenaSaPopustom, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </td>
                                <td>KM</td>
                                <td class="glyphicon-td" guid="@Model.PonudeJedinice[i].MyGuid">
                                    <span class="glyphicon glyphicon-remove" onclick="izbrisiRed('@Model.PonudeJedinice[i].MyGuid')"></span>
                                    @Html.HiddenFor(model => model.PonudeJedinice[i].MyGuid)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="button" id="btnDodajJedinicu" value="Dodaj Jedinicu" class="btn btn-default" onclick="dodajJedinicu()">Dodaj Jedinicu</button>
                    </div>
                </div>
                <hr />
                <h4>Ukljucene Aktivnosti</h4>
                <table width="800">
                    <thead>
                        <tr>
                            @*  <th><label class = "control-label col-md-12">Naziv Aktivnosti</label></th>*@
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Aktivnosti.Count; i++)
                        {
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            @Html.DropDownListFor(model => model.Aktivnosti[i].Aktivnost, new SelectList(Model.Aktivnosti[i].Aktivnosti, "Value", "Text", Model.Aktivnosti[i].Aktivnost), new { @class = "form-control ddlAktivnost", @onchange = "", @name = $"[{i}].Aktivnost", @style = "min-width: 500px;" })
                                            <div class="glyphicon-td" guid="@Model.Aktivnosti[i].MyGuid"><span class="glyphicon glyphicon-remove" onclick="izbrisiRed('@Model.Aktivnosti[i].MyGuid')"></span></div>
                                            @Html.HiddenFor(model => model.Aktivnosti[i].MyGuid)
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="form-group">
                    <div class="col-md-10">
                        <button type="button" id="btnDodajAktivnost" value="Dodaj Aktivnost" class="btn btn-default" onclick="dodajAktivnost()">Dodaj Aktivnost</button>
                    </div>
                </div>
                <input accept="image/*" onchange="ucitajImenaSlika()" type="file" id="slike" class="multiple" name="Slike" multiple style="display: none"/>
                <input type="button" class="btn btn-primary" onclick="dodajSlike()" value="Dodaj slike"/>
                <ul id="imenaSlika"></ul>
            </div>
            <div class="form-inline">
                <div class="form-group col-md-4" style="float: right;">
                    @Html.LabelFor(model => model.Popust, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Popust, new { htmlAttributes = new { @class = "form-control", @onchange = "izracunajPopust()" } })
                        @Html.ValidationMessageFor(model => model.Popust, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
        <br />
        <div>
            @Html.ActionLink("Nazad", "Index", new { }, new { @class= "btn btn-default" }) 
            <a href="javascript:pregledPonude();" class= "btn btn-default">Pregled ponude</a>
        </div>
    </div>
</div>

EtnoSelo.App/Views/Ponude/PregledPonude.cshtml
@model EtnoSelo.App.Models.PonudaModel
<div class="panel panel-primary">
    <div class="panel-heading">Pregled ponude</div>
    <div class="panel-body">
        <div>
            <hr />
            <div class="col-md-6">
                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.Naziv)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Naziv)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Popust)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Popust) %
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.VaziOd)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.VaziOd)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.VaziDo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.VaziDo)
                    </dd>
                </dl>
            </div>
        </div>
        <hr />

        <div>
            <hr />
            <h3>Stanbene Jedinice</h3>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PonudeJedinice.FirstOrDefault().TipStanbeneJedinice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PonudeJedinice.FirstOrDefault().StanbenaJedinica)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PonudeJedinice.FirstOrDefault().CijenaBezPopusta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PonudeJedinice.FirstOrDefault().CijenaSaPopustom)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.PonudeJedinice)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoviStanbenihJedinica.FirstOrDefault(x => x.Value == item.TipStanbeneJedinice.ToString()).Text)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StanbeneJedinice.FirstOrDefault(x => x.Id == item.StanbenaJedinica).Naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CijenaBezPopusta)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CijenaSaPopustom)
                        </td>
                    </tr>
                }

            </table>
        </div>
        <div>
            <h3>Ukljucene aktivnosti</h3>
            <table class="table">
                @foreach (var item in Model.Aktivnosti)
                {
                    <tr>
                        <td>
                            - @Html.DisplayFor(modelItem => item.Aktivnosti.FirstOrDefault(x => x.Value == item.Aktivnost.ToString()).Text)
                        </td>
                    </tr>
                }

            </table>
        </div>
        <div>
            @if (Model.Slike != null && Model.Slike.Count() > 0 && (string)ViewData["PreusmjeriNa"] == "KreirajPonudu")
            {
                <h3>Slike:</h3>
                <ul>
                    @foreach (var item in Model.Slike)
                    {
                        <li>@item.FileName</li>
                    }
                </ul>
            }
            @if ((string)ViewData["PreusmjeriNa"] != "KreirajPonudu")
            {
                <h3>Slike:</h3>
                <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-width: 200px; max-height: 200px; margin: 20px;">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        @foreach (var item in Model.NaziviSlika)
                        {
                            <div class="item @(item == Model.NaziviSlika[0] ? " active" : "")">
                                <img class="pregledSlikeImg" style="max-width: 200px; max-height: 200px;" src="@($"{Request.Url.Scheme}://{Request.Url.Authority}/Slike/Index?ponudaId={Model.Id}&naziv={item}")" alt="Chicago">
                            </div>
                        }
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            }
        </div>
        <p>
            @Html.ActionLink("Nazad", (string)ViewData["PreusmjeriNa"], new { kreirajNovu = false }, new { @class = "btn btn-default" }) 

            @if ((string)ViewData["PreusmjeriNa"] == "KreirajPonudu")
            {
                @Html.ActionLink("Potvrdi", "Snimi", new { }, new { @class = "btn btn-default" })
            }
        </p>
    </div>
</div>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Zatvori</span></button>
                <h4 class="modal-title" id="myModalLabel">Pregled slike</h4>
            </div>
            <div class="modal-body">
                <img src="" id="imagepreview" style="width: 400px; height: 264px;">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zatvori</button>
            </div>
        </div>
    </div>
</div>

EtnoSelo.App/Views/Ponude/temp.cshtml
@model IEnumerable<EtnoSelo.App.Models.PonudaJedinicaModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TipStanbeneJedinice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StanbenaJedinica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CijenaBezPopusta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CijenaSaPopustom)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TipStanbeneJedinice)
            @Html.DisplayFor(modelItem => item.TipoviStanbenihJedinica.FirstOrDefault(x => x.Value == item.TipStanbeneJedinice.ToString()).Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StanbeneJedinice.FirstOrDefault(x=>x.Id == item.StanbenaJedinica).Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CijenaBezPopusta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CijenaSaPopustom)
        </td>
    </tr>
}

</table>